spring:
  datasource:
    url: jdbc:postgresql://172.17.0.2:5432/shopee
    username: cuongha
    password: Cuong0701
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
logging:
  level:
    org.springframework.web.servlet.mvc.method.annotation: TRACE
    org.hibernate.SQL: DEBUG
shopee:
  app:
    jwtCookieName: shopee-cookie
    jwtSecret: b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    jwtExpirationMs: 60000
